<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>HUSTLE CULTURE</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-dark   " >
            <div class="container-fluid">
                <a class="navbar-brand" href=""><span   style="color: green">HUSTLE CULTURE</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        
                       
                           
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="categorias"><span style="color: white">CATEGORIAS</span></a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="home"><span style="color: white">PRODUCTOS EN VENTA</span></a>
                        </li>

                        <?php if (!isset($_SESSION['USER_ID'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="login"><span style="color: white">LOGIN</span></a>
                        </li>
                        <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="logout"><span style="color: white">LOGOUT (<?= $_SESSION['USER_USER'] ?>)</span></a>
                        </li>
                        <?php endif ?>
                    </ul>
            </div>
           
            </nav>
    </header>
    <main class="container mt-3">