<?php 
require_once './templates/header.phtml'?>



<form method="post" action="filtrarProducto" class="form-control form-control-sm mb-3">
    <div class="row flex-row align-items-center"> 
        <div class="col-auto">
            <label for="filtroCategoria" class="h5">Filtrar por:</label>
        </div>
        <div class="col-auto">
            <select class="form-select" name="filtroCategoria" id="filtroCategoria">
                <option value="">Todas las categorías</option> 
                <?php foreach($categorias as $item):?>
                    <option value="<?= $item->id_categoria?>"><?= $item->nombre_categoria?></option>
                <?php endforeach?>
            </select>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-success">Filtrar</button>
        </div>
    </div>
</form>

<table class="table table-striped table-hover" style="background-color: #aee6de;">
    <thead>
        <tr>
            <th>Nombre Producto</th>
            <th>categoria</th>
            <th>Precio</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list as $item):?>
            <tr>
                <td><?= $item->nombre_producto ?></td>
                <td><?= $item->nombre_categoria ?></td>
                <td><?= $item->precio ?></td>
                <td><?= $item->talle ?></td>
                <td><?= $item->color ?></td>
                <td><?= $item->marca ?></td>
                <td><a href="showProducto/<?= $item->id ?>" class="btn btn-success">Ver Producto</a></td>
            </tr>
        <?php endforeach?> 
    </tbody>
</table>

<?php require_once './templates/footer.phtml' ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
